# config.yaml

yolo:
  # YOLOv8-Pose 權重檔路徑
  weights: "src/model/YOLO/YOLO_weights/mouse_pose_yolo11L_150/weights/best.pt"
  # 信心門檻
  conf: 0.3
  # 輸入尺寸 (正方形邊長)
  input_size: 640
  # 原始影片長寬
  orig_size: [320, 240]
  #scale factor (將影像放大的倍數)
  scale_fadisplay_scale: 2.0


pose:
  # keypoint 歷史長度 (滑動平均)
  kp_history_len: 1
  vel_delta: 3
  pose_class_path: "classes.npy"

behavior:
  # 行為模型權重檔
  weights: "src\\model\\best_models\\best_epoch100_BehaviorBiLSTM_v3_3.pth"
  # weights:  "src\\model\\best_models\\best_epoch100_BehaviorTransformer_7.pth"
  # window size (累積__幀數處理)
  window_size: 96
  # rest 類別低信心時的 margin
  rest_prob_margin: 0.2
  # 其他類別最短持續幀數
  min_any_duration: 10
  # 要用哪個行為模型類別
  model: "BehaviorBiLSTM_v3"
  # model: "BehaviorTransformer"

paths:
  # 存 keypoints min/max 參數的 npz 檔
  minmax_npz: "minmax_values.npz"
  
