data:
  path: "data_prediction\\dataset\\kpt_gt_behavior\\kpts_with_gt_behavior_yolov11.csv"
  # path: "data_prediction\\dataset\\kpt_gt_behavior\\kpts_with_gt_behavior_yolov8.csv"

  orig_size: [320, 240]

sampling:
  num_per_class: 5000
  half_window: 48

# sliding_windows:
#   windows_size: 96
#   strides: 32


#速度、加速度隔幾幀看
vel_delta: 4

smooth:
  window_length: 1
  polyorder: 1

split:
  # test_size: 0.2
  val_size: 0.2
  # split_test_by_vid: false

# balancing:
#   strategy: "undersample"
#   target: "median"

dataloader:
  batch_size: 128
  for_lstm: false
  num_workers: 8 # 平行讀取 的子程序數量
  pin_memory: true # 優化 CPU→GPU 的記憶體copy

train:
  epochs:       10
  lr:           1e-3         # base_lr
  warmup_epochs: 0           # 前 5 個 epoch 做 warm‐up
  device:       "cuda"
  seed:         42
  label_smoothing: 0
  # weight:   [1.0, 1.2, 0.8, 1.5, 1.1, 1.0, 1.3]
  weight: [1.0, 1.0, 0.9, 1.2, 1.0, 0.9, 1.1]
  rest_threshold: 0.85


optimizer:
  type:          "AdamW"
  betas:         [0.9, 0.999]
  eps:           1e-8
  weight_decay:  1e-3

scheduler:
  plateau:
    mode:       min
    factor:     0.5
    patience:   2
    threshold:  0.0001
    min_lr:     1e-6


#================== models ==================

# model:
#   name: "BehaviorBiLSTM_v3"
#   params:
#     hidden_dim: 64                # 可自行調大（128/256）
#     num_layers: 3
#     dropout_p: 0.2
#     se_ratio: 16
  

model:
  name: "SimpleSTTR_BiLSTM"         
  params:
    d_model:     64                 # Transformer 隱層維度
    num_heads:   4                   # Multi-Head Attention 頭數
    lstm_hidden: 64                  # Bi-LSTM hidden size
    lstm_layers: 3                   # Bi-LSTM 疊層數
    dropout_p:   0.2                 # Dropout(統一用)
    num_classes: 7                   # 必填：行為類別數


# model:
#   name: "SimpleSTTR_BiLSTM_v2"         
#   params:
#     d_model:     64                 # Transformer 隱層維度
#     sttr_dropout_p: 0.15
#     num_heads:   4                   # Multi-Head Attention 頭數
#     lstm_hidden: 64                  # Bi-LSTM hidden size
#     lstm_layers: 3                   # Bi-LSTM 疊層數
#     se_ratio:   8
#     lstm_dropout_p: 0.15                 # Dropout
#     num_classes: 7                  

# model:
#   name: "LSTM_Transformer"         
#   params:
#     d_model:     64                 # Transformer 隱層維度
#     num_heads:   4                   # Multi-Head Attention 頭數
#     lstm_hidden: 64                  # Bi-LSTM hidden size
#     lstm_layers: 3                   # Bi-LSTM 疊層數
#     dropout_p:   0.15                 # Dropout(統一用)
#     num_classes: 7                   # 必填：行為類別數

# model:
#   name: "SimpleSTTR"          
#   params:
#     d_model:     128                 # Transformer 隱層維度
#     num_heads:   4                   # Multi-Head Attention 頭數
#     num_classes: 7                   # 必填：行為類別數

# model:
#   name: "STTRNet"
#   params:
#     num_classes: 7
#     # 前段 ST‐GCN Block 
#     stgcn_channels: [64, 128]

#     # 2) S-TR / T-TR 每一層的 d_model 
#     sttr_dims: [128, 128]    
#     num_heads : 8

#     # 4) STGCNBlock 內的時域卷積 kernel size
#     t_kernel  : 3

#     # 5. Dropout 比例 (同時傳給 STRBlock/TTRBlock)
#     dropout   : 0.1

#     # 6. 幾層 S-TR / T-TR
#     num_layers: 2

# model:
#   name: "STTR_BiLSTM"
#   params:
#     num_classes: 7
#     stgcn_channels: [ 64]
#     sttr_dims: [64, 64]    
#     num_heads: 4
#     tcn_kernel: 9
#     dropout: 0.2
#     num_layers: 2
#     # BiLSTM
#     lstm_input: 71
#     lstm_hidden : 64
#     lstm_layers : 2
#     se_ratio : 16
#     dropout_p : 0.15





save:
  model_folder: "src\\model\\Behavior_models\\best_models"  
  metrics_folder: "C:\\Users\\micha\\Desktop\\behaviors_model_metrics"

